#!/bin/bash

# Define colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Retrieve the current branch name
branch_name=$(git symbolic-ref --short HEAD)

# Define your branch naming convention (regex pattern)
pattern="^(feature|bugfix|hotfix|release)\/[0-9]+-[a-zA-Z0-9_-]+$"

# Check if the branch name matches the pattern
if [[ "$branch_name" =~ $pattern ]]; then
	echo -e "${GREEN}Success: Branch name follows the required format.${NC}"
else
	echo -e "${RED}Error: Your commit was rejected due to invalid branch name.${NC}"
	echo -e "${YELLOW}Info: Please ensure the branch name follows the required pattern -${NC}"
	echo -e "${NC}[feature/bugfix/hotfix/release]/[Ticket Number]-branch-name ${GREEN} Example -> feature/82345-loan-viewer-changes ${NC}"
	echo -e "${NC} y***********s***********i ${NC}"
	echo -e "${YELLOW}Info: Follow these steps to rename your branch - ${NC}"
	echo -e "${NC} - First, ensure you're not currently on the branch you want to rename."
	echo -e "${NC} - Rename the Branch: Use the git checkout -b command followed by the old branch name and
   the new branch name, also don't forget to delete old branch.${GREEN}
   Example -> git checkout -b new-branch-name old-branch-name && git branch -D old-branch-name ${NC}"
	echo -e "${NC} y***********s***********i ${NC}"
	exit 1
fi
