spring:
  profiles:
    active: pre-prod
  application:
    name: collection-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      label: preprod
#      uri: http://13.232.9.69:8888
  flyway:
    enabled: false
    default-schema: flyway
    schemas:
      - flyway
    baseline-on-migrate: true
    baseline-version: 0
    table: flyway_schema_history_collection
    common-migration-files-location: classpath:db/migration/common
    client-specific-Migration-files-location: classpath:db/migration/clients/
  kafka:
    events:
      topic: collection_receipt_checked_preprod
    groupId: collection-preprod

