server:
  servlet: /collection-service
    context-path:
  port: '1101'

spring:
  redis:
    database: '0'
    password: redis@1234
    host: 13.232.9.69
    port: '6380'
    timeout: '60000'
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    basic:
      enabled: false
  management:
    security:
      enabled: false


datasource:
  collection:
    driver-class-name: org.postgresql.Driver
    username: lms_preprod
    password: Z6ns4UZ&7p7S
    jdbc-url: jdbc:postgresql://172.31.13.59:5432/
    connection-properties: ?ApplicationName=${spring.application.name}

logging:
  level:
    com:
      zaxxer:
        hikari: DEBUG

clientList:
  api:
    url: http://172.31.13.59:9053/v1/client
