server:
  servlet:
    context-path: /collection-service
  port: '9002'

spring:
  redis:
    database: '0'
    password: redis@1234
    host: 13.232.9.69
    port: '6380'
    timeout: '60000'
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    basic:
    enabled: false
  management:
    security:
      enabled: false


datasource:
  collection:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ajay503
    jdbc-url: jdbc:postgresql://localhost:5432/
    connection-properties: ?ApplicationName=${spring.application.name}

logging:
  level:
    com:
      zaxxer:
        hikari: DEBUG

clientList:
  api:
    url: http://13.232.9.69:9053/v1/client
