spring:
  profiles:
    active: dev
  application:
    name: collection-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      label: dev
  flyway:
    default-schema: flyway
    enabled: false
    schemas:
      - flyway
    baseline-on-migrate:
    baseline-version: 0
    table: flyway_schema_history_collection
    common-migration-files-location: classpath:db/migration/common
    client-specific-Migration-files-location: classpath:db/migration/clients/

